#!/usr/bin/env python3
"""
Exports fbc_history.db (built by build_dataset.py) into a plain SQL dump
that Cloudflare D1 can import via:

    wrangler d1 execute fbc-history --remote --file=./d1_data.sql

D1 is SQLite under the hood, but `wrangler d1 execute` imports a file as a
sequence of statements rather than a live SQLite connection, so this writes
batched multi-row INSERTs (a few hundred rows each) instead of one INSERT
per row -- keeps the file small and the import fast for ~7k rows.

Usage:
    python3 export_to_d1.py fbc_history.db d1_data.sql
"""
import sqlite3
import sys

BATCH_SIZE = 200

COLUMNS = [
    "date", "counter", "isin", "market", "sector",
    "shares_in_issue", "mkt_cap_usd_ibr", "open_price_zig", "close",
    "usd_price_ibr", "change_pct", "volume", "value_traded_zig",
    "div_yield_fy25", "div_yield_fy26", "ytd_gain_loss",
    "chg_pct_filled", "roll5_chg", "roll20_std_chg", "traded",
]


def sql_literal(v):
    if v is None:
        return "NULL"
    if isinstance(v, float):
        # D1/SQLite accept plain float literals; guard against NaN/inf,
        # which aren't valid SQL literals.
        if v != v or v in (float("inf"), float("-inf")):
            return "NULL"
        return repr(v)
    if isinstance(v, int):
        return str(v)
    # text: escape single quotes the SQL way
    return "'" + str(v).replace("'", "''") + "'"


def export(db_path, out_path):
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    rows = conn.execute(f"SELECT {', '.join(COLUMNS)} FROM prices ORDER BY date, counter").fetchall()
    conn.close()

    if not rows:
        raise ValueError(f"No rows found in {db_path} -- run build_dataset.py first.")

    col_list = ", ".join(f'"{c}"' for c in COLUMNS)
    lines = [
        "-- Auto-generated by export_to_d1.py -- do not hand-edit.",
        "-- Re-run build_dataset.py + export_to_d1.py to refresh, then re-import.",
        "DELETE FROM prices;",
    ]

    for i in range(0, len(rows), BATCH_SIZE):
        batch = rows[i : i + BATCH_SIZE]
        value_tuples = []
        for row in batch:
            values = ", ".join(sql_literal(row[c]) for c in COLUMNS)
            value_tuples.append(f"({values})")
        lines.append(f"INSERT INTO prices ({col_list}) VALUES\n  " + ",\n  ".join(value_tuples) + ";")

    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {out_path} -- {len(rows):,} rows in {(len(rows) + BATCH_SIZE - 1)//BATCH_SIZE} batched INSERTs.")


if __name__ == "__main__":
    db_path = sys.argv[1] if len(sys.argv) > 1 else "../fbc_history.db"
    out_path = sys.argv[2] if len(sys.argv) > 2 else "d1_data.sql"
    export(db_path, out_path)
