#!/usr/bin/env python3
"""
Exports fbc_history.db (built by build_dataset.py) into a plain SQL dump
that Cloudflare D1 can import via:

    wrangler d1 execute fbc-history --remote --file=./d1_data.sql

D1 is SQLite under the hood, but `wrangler d1 execute` imports a file as a
sequence of statements rather than a live SQLite connection, so this writes
batched multi-row INSERTs (a few hundred rows each) instead of one INSERT
per row -- keeps the file small and the import fast for ~7k rows.

It also loads predictions.json (the latest model run) into the `predictions`
and `model_track_record` tables, so the chatbot can answer questions about
the watchlist and its track record. Those tables are left empty if the file
is missing.

Usage:
    python3 export_to_d1.py fbc_history.db d1_data.sql [predictions.json]
"""
import json
import os
import sqlite3
import sys

BATCH_SIZE = 200

COLUMNS = [
    "date", "counter", "isin", "market", "sector",
    "shares_in_issue", "mkt_cap_usd_ibr", "open_price_zig", "close",
    "usd_price_ibr", "change_pct", "volume", "value_traded_zig",
    "div_yield_fy25", "div_yield_fy26", "ytd_gain_loss",
    "chg_pct_filled", "roll5_chg", "roll20_std_chg", "traded",
    "usd_return_pct", "return_since",
]

PREDICTION_COLUMNS = [
    "price_date", "counter", "market", "sector", "close", "usd_price",
    "today_chg_pct", "traded_today", "predicted_chg_pct", "risk_score",
    "volatility_band", "days_traded_20", "signal", "watchlist_rank",
]

TRACK_RECORD_COLUMNS = [
    "price_date", "training_days", "days", "beat_market_days",
    "beat_market_days_pct", "picks_avg_next_day_pct", "market_avg_next_day_pct",
    "biggest_fallers_avg_next_day_pct", "picks_total", "picks_rose_next_day_pct",
    "picks_flat_next_day_pct", "picks_fell_next_day_pct", "holdout_days",
    "model_mae", "no_change_mae",
]

HERE = os.path.dirname(os.path.abspath(__file__))
SCHEMA_PATH = os.path.join(HERE, "schema.sql")
DEFAULT_PREDICTIONS_PATH = os.path.join(HERE, "..", "..", "predictions.json")


def sql_literal(v):
    if v is None:
        return "NULL"
    if isinstance(v, float):
        # D1/SQLite accept plain float literals; guard against NaN/inf,
        # which aren't valid SQL literals.
        if v != v or v in (float("inf"), float("-inf")):
            return "NULL"
        return repr(v)
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, int):
        return str(v)
    # text: escape single quotes the SQL way
    return "'" + str(v).replace("'", "''") + "'"


def insert_statements(table, columns, rows):
    """Batched multi-row INSERTs for `rows` (mappings keyed by column name)."""
    col_list = ", ".join(f'"{c}"' for c in columns)
    statements = []
    for i in range(0, len(rows), BATCH_SIZE):
        value_tuples = [
            "(" + ", ".join(sql_literal(row[c]) for c in columns) + ")"
            for row in rows[i : i + BATCH_SIZE]
        ]
        statements.append(f"INSERT INTO {table} ({col_list}) VALUES\n  " + ",\n  ".join(value_tuples) + ";")
    return statements


def prediction_rows(predictions_path):
    """(predictions rows, model_track_record rows) from predictions.json, or two
    empty lists when the file is missing."""
    if not os.path.exists(predictions_path):
        print(f"No {predictions_path} -- leaving the predictions tables empty.")
        return [], []
    with open(predictions_path) as f:
        snap = json.load(f)
    price_date = snap.get("price_date")
    ranks = {p["counter"]: i + 1 for i, p in enumerate(snap.get("watchlist") or [])}
    preds = [
        {**p, "price_date": price_date, "watchlist_rank": ranks.get(p["counter"])}
        for p in snap.get("all_predictions") or []
    ]
    record = {
        "price_date": price_date,
        "training_days": snap.get("training_days"),
        **(snap.get("track_record") or {}),
        **(snap.get("accuracy") or {}),
    }
    return preds, [{c: record.get(c) for c in TRACK_RECORD_COLUMNS}]


def export(db_path, out_path, predictions_path=DEFAULT_PREDICTIONS_PATH):
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    rows = conn.execute(f"SELECT {', '.join(COLUMNS)} FROM prices ORDER BY date, counter").fetchall()
    conn.close()

    if not rows:
        raise ValueError(f"No rows found in {db_path} -- run build_dataset.py first.")

    # The schema is recreated on every import rather than DELETE-ing rows, so a
    # column added to schema.sql reaches D1 with the next daily refresh instead
    # of failing the INSERTs against the old table.
    with open(SCHEMA_PATH) as f:
        schema = f.read()
    lines = [
        "-- Auto-generated by export_to_d1.py -- do not hand-edit.",
        "-- Re-run build_dataset.py + export_to_d1.py to refresh, then re-import.",
        schema.strip(),
    ]

    lines += insert_statements("prices", COLUMNS, rows)
    preds, record = prediction_rows(predictions_path)
    lines += insert_statements("predictions", PREDICTION_COLUMNS, preds)
    lines += insert_statements("model_track_record", TRACK_RECORD_COLUMNS, record)

    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {out_path} -- {len(rows):,} price rows, {len(preds)} prediction rows.")


if __name__ == "__main__":
    db_path = sys.argv[1] if len(sys.argv) > 1 else "../fbc_history.db"
    out_path = sys.argv[2] if len(sys.argv) > 2 else "d1_data.sql"
    predictions_path = sys.argv[3] if len(sys.argv) > 3 else DEFAULT_PREDICTIONS_PATH
    export(db_path, out_path, predictions_path)
